# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BubbleBlastSaga' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'PhysicsEngine', :git => 'https://github.com/cs3217/2018-ps4-thenaesh', :branch => 'cocoapod'
end
